### ISSUE TITLE
CreateAppend not meet GSP-134 Write Behavior Consistency

### ISSUE THREAD

**Issue by JinnyYi** [beyondstorage/go-service-qingstor#83]
`AppendObject` doesn't support overwrite. `CreateAppend` to an existing appendable object with size greater than 0 will get `"code":"invalid_argument","message":"position must equal to the current object size, position=0, object size=xxx"`, which not meet [GSP-134: Write Behavior Consistency](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/134-write-behavior-consistency.md).

**Comment by Xuanwo** [comment]
I think we need to remove the file before creating it.

**Comment by Xuanwo** [comment]
Fixed in #84
